### ISSUE TITLE
index.html: post listing text is not responsive

### ISSUE THREAD

**Issue by pozogo** [MinionAddicts/WeLiveInASociety#8]
on smaller screens the font size should dynamically adjust to be smaller and more readable
![image](https://user-images.githubusercontent.com/30553505/139696687-9e356711-c891-445c-90c0-94a75c5f790d.png)

**Comment by MarkJaco** [comment]
Oh damn, I'll fix it tomorrow

**Comment by pozogo** [comment]
A step in the right direction, but it looks extremely small on mobile now.
What you want to do is use @media queries in the CSS to change the font size in discrete steps depending on the screen size. 
So like, e.g:
```
make the font-size 35px.
If the screen's width is greater than 768px, override the font-size to 65px
If the screen's width is greater than 992px, override the font-size to 80px
```
For reference, an implementation of the example I gave above can be found here: https://github.com/MinionAddicts/WeLiveInASociety/blob/9aa02200179b77698569fb4ff366cafb9ab80a6d/res/style.css#L61-L85

![image](https://user-images.githubusercontent.com/30553505/140180663-dfea6013-6d65-4860-8a54-67edb589d940.png)
